language: android

branches:
  except:
    # Don't run on tag pushes
    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10

android:
  update_sdk: true
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - android-25
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

  # report coverage
  - bash <(curl -s https://codecov.io/bash)

  # create tag
  - git config --global user.email "ci@smartcar.com"
  - git config --global user.name "Travis CI User"
  - export SDK_VERSION=$(cat smartcar-auth/gradle.properties | grep -E '^libVersion=.*$' | sed 's/^libVersion=//')
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then git tag -a "v${SDK_VERSION}" -m "Travis Generated Tag"; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc && git push origin "v${SDK_VERSION}"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew install bintrayUpload
    on:
      branch: master
