language: android

branches:
  except:
    # Don't run on tag pushes
    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - BUILD_TOOLS_VERSION=29.0.2
    - ANDROID_API_LEVEL=29
    - ANDROID_ABI=x86
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOLS
    - android-$ANDROID_API_LEVEL
    - sys-image-$ANDROID_ABI-android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - yes | sdkmanager --update
  - sdkmanager tools
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - ./gradlew connectedCheck

  # report coverage
  - bash <(curl -s https://codecov.io/bash)

  # create tag
  - git config --global user.email "ci@smartcar.com"
  - git config --global user.name "Travis CI User"
  - export SDK_VERSION=$(cat smartcar-auth/gradle.properties | grep -E '^libVersion=.*$' | sed 's/^libVersion=//')
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then git tag -a "v${SDK_VERSION}" -m "Travis Generated Tag"; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc && git push origin "v${SDK_VERSION}"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew install bintrayUpload
    on:
      branch: master
